"""Build one fixed AA4 atlas for Canvas and emWin 5.22. No runtime OS fonts."""
import hashlib, json, math, pathlib, sys, shutil
ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB = ROOT/('public' if (ROOT/'public').exists() else 'dist')
sys.path.insert(0, str(ROOT / 'artifacts/font-deps'))
from PIL import Image, ImageDraw, ImageFont, __version__ as pillow_version
from fontTools.ttLib import TTFont

source = json.loads((WEB/'generated/source.json').read_text(encoding='utf-8'))
locales = json.loads((WEB/'locales/overrides.json').read_text(encoding='utf-8'))
chars = set(''.join(v for lang in locales['languages'] for v in lang['strings'].values()))
fonts = dict(source['fonts'])
assets = ROOT/'assets/fonts'
names = ['NotoSansCJKsc-Regular.otf', 'NotoSans-Regular.ttf']
faces = [ImageFont.truetype(str(assets/name), 15, layout_engine=ImageFont.Layout.BASIC) for name in names]
maps = [TTFont(assets/name).getBestCmap() for name in names]
for char in sorted(chars):
    if char in fonts: continue
    index = 0 if ord(char) >= 0x2e80 else 1
    if ord(char) not in maps[index]: raise ValueError('Missing source glyph: '+char)
    face = faces[index]
    # Draw at an explicit baseline, then retain exact bearings; never crop silently.
    image = Image.new('L', (40,40))
    ImageDraw.Draw(image).text((8, 13+8), char, font=face, fill=255, anchor='ls')
    box=image.getbbox()
    if box is None: raise ValueError('Unexpected blank glyph: '+char)
    left,top,right,bottom=box
    # CJK ink occasionally descends below baseline+3; lift only enough for 16px cell.
    offset_y=(16-(bottom-top))//2 if index==0 else top-8
    if index!=0 and bottom-8>16: offset_y-=bottom-8-16
    if offset_y<0: raise ValueError('Glyph exceeds 16px cell: '+char)
    crop=image.crop(box); w,h=crop.size
    packed=[]
    for y in range(h):
        for x in range(0,w,2):
            hi=(crop.getpixel((x,y))*15+127)//255
            lo=(crop.getpixel((x+1,y))*15+127)//255 if x+1<w else 0
            packed.append((hi<<4)|lo)
    fonts[char]={'w':w,'h':h,'x':(16-w)//2 if index==0 else left-8,'y':offset_y,'advance':16 if index==0 else math.ceil(face.getlength(char)), 'bytes':packed}
fonts=dict(sorted(fonts.items(), key=lambda item:ord(item[0])))
metadata={'format':'AA4_EXT high nibble first; each row padded to byte', 'height':16,
          'baseline':13,'pillow':pillow_version,'glyphCount':len(fonts),
          'bitmapBytes':sum(len(g['bytes']) for g in fonts.values()),
          'inputs':{name:hashlib.sha256((assets/name).read_bytes()).hexdigest() for name in names},
          'originalASCII':source['hashes'].get('Font/Helvetica16.c'),
          'licenseNotices':['licenses/FONT-NOTICES.md','licenses/OFL-CJK.txt','licenses/OFL-NotoSans.txt'],
          'note':'ASCII retained from supplied firmware; new CJK/Cyrillic from Noto under OFL, not legacy Chinese restoration.'}
atlas={'metadata':metadata, 'glyphs':fonts}
out=WEB/'generated/menu-font.json'
out.write_text(json.dumps(atlas,ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')
firmware=ROOT/'firmware/shared'; firmware.mkdir(parents=True,exist_ok=True)
header='''/* Generated fixed bitmap font. See FONT-NOTICES.md and OFL notices. */
#ifndef M1_MENU_FONT_H
#define M1_MENU_FONT_H
#include "GUI.h"
extern GUI_CONST_STORAGE GUI_FONT GUI_FontM1Menu;
#define GUI_FONT_M1_MENU (&GUI_FontM1Menu)
#endif
'''
(firmware/'m1_menu_font.h').write_text(header,encoding='ascii')
lines=['/* Generated by tools/build-fonts.py; exact bytes of public/generated/menu-font.json. */',
       '/* See FONT-NOTICES.md: original ASCII license + OFL CJK/Cyrillic. */', '#include "m1_menu_font.h"']
codes=[]
for char,g in fonts.items():
    code=f'{ord(char):04X}'; codes.append(code)
    lines.append(f'static GUI_CONST_STORAGE unsigned char bitmap_{code}[] = {{'+','.join(f'0x{v:02X}' for v in g['bytes'])+'};')
    lines.append(f'static GUI_CONST_STORAGE GUI_CHARINFO_EXT glyph_{code} = {{'+','.join(str(g[k]) for k in ['w','h','x','y','advance'])+f',bitmap_{code}'+'};')
next_block='0'
for code in reversed(codes):
    lines.append(f'static GUI_CONST_STORAGE GUI_FONT_PROP_EXT block_{code} = {{0x{code},0x{code},&glyph_{code},{next_block}}};')
    next_block=f'&block_{code}'
lines.append('GUI_CONST_STORAGE GUI_FONT GUI_FontM1Menu = {GUI_FONTTYPE_PROP_AA4_EXT,16,16,1,1,{'+next_block+'},13,9,12};')
(firmware/'m1_menu_font.c').write_text('\n'.join(lines)+'\n',encoding='ascii')
(firmware/'font-manifest.json').write_text(json.dumps(metadata,indent=2)+'\n',encoding='utf-8')
notices=WEB/'licenses'; notices.mkdir(exist_ok=True)
for name in ['OFL-CJK.txt','OFL-NotoSans.txt']: shutil.copyfile(assets/name,notices/name)
shutil.copyfile(ROOT/'firmware/FONT-NOTICES.md',notices/'FONT-NOTICES.md')
print(json.dumps(metadata))
